use std::io::{Read, Write};
use io::Result;
use protocol::*;
 use protocol::game::data::items::ObjectItem;
impl_type!(ChatAbstractClientMessage, 850, content| String);
impl_type!(ChatAbstractServerMessage, 880, channel| i8, content| String, timestamp| i32, fingerprint| String);
impl_type!(ChatAdminServerMessage, 6135, base| ChatServerMessage);
impl_type!(ChatClientMultiMessage, 861, base| ChatAbstractClientMessage, channel| i8);
impl_type!(ChatClientMultiWithObjectMessage, 862, base| ChatClientMultiMessage, objects| Vec<ObjectItem>);
impl_type!(ChatClientPrivateMessage, 851, base| ChatAbstractClientMessage, receiver| String);
impl_type!(ChatClientPrivateWithObjectMessage, 852, base| ChatClientPrivateMessage, objects| Vec<ObjectItem>);
impl_type!(ChatErrorMessage, 870, reason| i8);
impl_type!(ChatServerCopyMessage, 882, base| ChatAbstractServerMessage, receiver_id| VarInt, receiver_name| String);
impl_type!(ChatServerCopyWithObjectMessage, 884, base| ChatServerCopyMessage, objects| Vec<ObjectItem>);
impl_type!(ChatServerMessage, 881, base| ChatAbstractServerMessage, sender_id| i32, sender_name| String, sender_account_id| i32);
impl_type!(ChatServerWithObjectMessage, 883, base| ChatServerMessage, objects| Vec<ObjectItem>);
