use std::io::{Read, Write};
use io::Result;
use protocol::*;
 use protocol::game::look::EntityLook;
impl_type!(ContactLookErrorMessage, 6045, request_id| VarInt);
impl_type!(ContactLookMessage, 5934, request_id| VarInt, player_name| String, player_id| VarInt, look| EntityLook);
impl_type!(ContactLookRequestByIdMessage, 5935, base| ContactLookRequestMessage, player_id| VarInt);
impl_type!(ContactLookRequestMessage, 5932, request_id| i8, contact_type| i8);
 use protocol::game::context::roleplay::BasicNamedAllianceInformations;
impl_type!(AbstractSocialGroupInfos, 416);
impl_type!(AlliancedGuildFactSheetInformations, 422, base| GuildInformations, alliance_infos| BasicNamedAllianceInformations);
impl_type!(AllianceFactSheetInformations, 421, base| AllianceInformations, creation_date| i32);
impl_type!(AllianceVersatileInformations, 432, alliance_id| VarInt, nb_guilds| VarShort, nb_members| VarShort, nb_subarea| VarShort);
impl_type!(GuildFactSheetInformations, 424, base| GuildInformations, leader_id| VarInt, guild_level| i8, nb_members| VarShort);
impl_type!(GuildInAllianceVersatileInformations, 437, base| GuildVersatileInformations, alliance_id| VarInt);
impl_type!(GuildInsiderFactSheetInformations, 423, base| GuildFactSheetInformations, leader_name| String, nb_connected_members| VarShort, nb_tax_collectors| i8, last_activity| i32, enabled| bool);
impl_type!(GuildVersatileInformations, 435, guild_id| VarInt, leader_id| VarInt, guild_level| i8, nb_members| i8);
