use std::io::{Read, Write};
use std::io::Result;
use protocol::*;
 use types::game::look::EntityLook; use types::game::context::roleplay::BasicGuildInformations; use variants::PlayerStatusVariant;
impl_type!(AbstractContactInformations, 380, account_id| i32, account_name| String);
impl_type!(FriendInformations, 78, base| AbstractContactInformations, player_state| i8, last_connection| VarShort, achievement_points| i32);
impl_type!(FriendOnlineInformations, 92, base| FriendInformations, player_id| VarLong, player_name| String, level| i8, alignment_side| i8, breed| i8, sex| bool, guild_info| BasicGuildInformations, mood_smiley_id| VarShort, status| PlayerStatusVariant);
impl_type!(FriendSpouseInformations, 77, spouse_account_id| i32, spouse_id| VarLong, spouse_name| String, spouse_level| i8, breed| i8, sex| i8, spouse_entity_look| EntityLook, guild_info| BasicGuildInformations, alignment_side| i8);
impl_type!(FriendSpouseOnlineInformations, 93, base| FriendSpouseInformations, in_fight| Flag, follow_spouse| Flag, map_id| i32, sub_area_id| VarShort);
impl_type!(IgnoredInformations, 106, base| AbstractContactInformations);
impl_type!(IgnoredOnlineInformations, 105, base| IgnoredInformations, player_id| VarLong, player_name| String, breed| i8, sex| bool);
