use std::io::{Read, Write};
use io::Result;
use protocol::*;

impl_type!(FriendAddedMessage, 5599, friend_added| FriendInformationsVariant);
impl_type!(FriendAddFailureMessage, 5600, reason| i8);
impl_type!(FriendAddRequestMessage, 4004, name| String);
impl_type!(FriendDeleteRequestMessage, 5603, account_id| i32);
impl_type!(FriendDeleteResultMessage, 5601, success| bool, name| String);
impl_type!(FriendJoinRequestMessage, 5605, name| String);
impl_type!(FriendSetWarnOnConnectionMessage, 5602, enable| bool);
impl_type!(FriendSetWarnOnLevelGainMessage, 6077, enable| bool);
impl_type!(FriendsGetListMessage, 4001);
impl_type!(FriendsListMessage, 4002, friends_list| Vec<FriendInformationsVariant>);
impl_type!(FriendSpouseFollowWithCompassRequestMessage, 5606, enable| bool);
impl_type!(FriendSpouseJoinRequestMessage, 5604);
impl_type!(FriendUpdateMessage, 5924, friend_updated| FriendInformationsVariant);
impl_type!(FriendWarnOnConnectionStateMessage, 5630, enable| bool);
impl_type!(FriendWarnOnLevelGainStateMessage, 6078, enable| bool);
impl_type!(GuildMemberSetWarnOnConnectionMessage, 6159, enable| bool);
impl_type!(GuildMemberWarnOnConnectionStateMessage, 6160, enable| bool);
impl_type!(IgnoredAddedMessage, 5678, ignore_added| IgnoredInformationsVariant, session| bool);
impl_type!(IgnoredAddFailureMessage, 5679, reason| i8);
impl_type!(IgnoredAddRequestMessage, 5673, name| String, session| bool);
impl_type!(IgnoredDeleteRequestMessage, 5680, account_id| i32, session| bool);
impl_type!(IgnoredDeleteResultMessage, 5677, success| Flag, session| Flag, name| String);
impl_type!(IgnoredGetListMessage, 5676);
impl_type!(IgnoredListMessage, 5674, ignored_list| Vec<IgnoredInformationsVariant>);
impl_type!(SpouseGetInformationsMessage, 6355);
impl_type!(SpouseInformationsMessage, 6356, spouse| FriendSpouseInformationsVariant);
impl_type!(SpouseStatusMessage, 6265, has_spouse| bool);
impl_type!(WarnOnPermaDeathStateMessage, 6513, enable| bool);
 use protocol::game::character::status::PlayerStatusVariant; use protocol::game::context::roleplay::BasicGuildInformations; use protocol::game::look::EntityLook;
impl_type!(AbstractContactInformations, 380, account_id| i32, account_name| String);
impl_type!(FriendInformations, 78, base| AbstractContactInformations, player_state| i8, last_connection| VarShort, achievement_points| i32);
impl_type!(FriendOnlineInformations, 92, base| FriendInformations, player_id| VarInt, player_name| String, level| i8, alignment_side| i8, breed| i8, sex| bool, guild_info| BasicGuildInformations, mood_smiley_id| i8, status| PlayerStatusVariant);
impl_type!(FriendSpouseInformations, 77, spouse_account_id| i32, spouse_id| VarInt, spouse_name| String, spouse_level| i8, breed| i8, sex| i8, spouse_entity_look| EntityLook, guild_info| BasicGuildInformations, alignment_side| i8);
impl_type!(FriendSpouseOnlineInformations, 93, base| FriendSpouseInformations, in_fight| Flag, follow_spouse| Flag, map_id| i32, sub_area_id| VarShort);
impl_type!(IgnoredInformations, 106, base| AbstractContactInformations);
impl_type!(IgnoredOnlineInformations, 105, base| IgnoredInformations, player_id| VarInt, player_name| String, breed| i8, sex| bool);
