use std::io::{Read, Write};
use io::Result;
use protocol::*;
 use protocol::game::look::EntityLook;
impl_type!(AbstractGameActionFightTargetedAbilityMessage, 6118, base| AbstractGameActionMessage, target_id| i32, destination_cell_id| i16, critical| i8, silent_cast| bool);
impl_type!(GameActionFightActivateGlyphTrapMessage, 6545, base| AbstractGameActionMessage, mark_id| i16, active| bool);
impl_type!(GameActionFightCarryCharacterMessage, 5830, base| AbstractGameActionMessage, target_id| i32, cell_id| i16);
impl_type!(GameActionFightCastOnTargetRequestMessage, 6330, spell_id| VarShort, target_id| i32);
impl_type!(GameActionFightCastRequestMessage, 1005, spell_id| VarShort, cell_id| i16);
impl_type!(GameActionFightChangeLookMessage, 5532, base| AbstractGameActionMessage, target_id| i32, entity_look| EntityLook);
impl_type!(GameActionFightCloseCombatMessage, 6116, base| AbstractGameActionFightTargetedAbilityMessage, weapon_generic_id| VarShort);
impl_type!(GameActionFightDeathMessage, 1099, base| AbstractGameActionMessage, target_id| i32);
impl_type!(GameActionFightDispellableEffectMessage, 6070, base| AbstractGameActionMessage, effect| AbstractFightDispellableEffectVariant);
impl_type!(GameActionFightDispellEffectMessage, 6113, base| GameActionFightDispellMessage, boost_u_i_d| i32);
impl_type!(GameActionFightDispellMessage, 5533, base| AbstractGameActionMessage, target_id| i32);
impl_type!(GameActionFightDispellSpellMessage, 6176, base| GameActionFightDispellMessage, spell_id| VarShort);
impl_type!(GameActionFightDodgePointLossMessage, 5828, base| AbstractGameActionMessage, target_id| i32, amount| VarShort);
impl_type!(GameActionFightDropCharacterMessage, 5826, base| AbstractGameActionMessage, target_id| i32, cell_id| i16);
impl_type!(GameActionFightExchangePositionsMessage, 5527, base| AbstractGameActionMessage, target_id| i32, caster_cell_id| i16, target_cell_id| i16);
impl_type!(GameActionFightInvisibilityMessage, 5821, base| AbstractGameActionMessage, target_id| i32, state| i8);
impl_type!(GameActionFightInvisibleDetectedMessage, 6320, base| AbstractGameActionMessage, target_id| i32, cell_id| i16);
impl_type!(GameActionFightInvisibleObstacleMessage, 5820, base| AbstractGameActionMessage, source_spell_id| VarInt);
impl_type!(GameActionFightKillMessage, 5571, base| AbstractGameActionMessage, target_id| i32);
impl_type!(GameActionFightLifeAndShieldPointsLostMessage, 6310, base| GameActionFightLifePointsLostMessage, shield_loss| VarShort);
impl_type!(GameActionFightLifePointsGainMessage, 6311, base| AbstractGameActionMessage, target_id| i32, delta| VarInt);
impl_type!(GameActionFightLifePointsLostMessage, 6312, base| AbstractGameActionMessage, target_id| i32, loss| VarShort, permanent_damages| VarShort);
impl_type!(GameActionFightMarkCellsMessage, 5540, base| AbstractGameActionMessage, mark| GameActionMark);
impl_type!(GameActionFightModifyEffectsDurationMessage, 6304, base| AbstractGameActionMessage, target_id| i32, delta| i16);
impl_type!(GameActionFightNoSpellCastMessage, 6132, spell_level_id| VarInt);
impl_type!(GameActionFightPointsVariationMessage, 1030, base| AbstractGameActionMessage, target_id| i32, delta| i16);
impl_type!(GameActionFightReduceDamagesMessage, 5526, base| AbstractGameActionMessage, target_id| i32, amount| VarInt);
impl_type!(GameActionFightReflectDamagesMessage, 5530, base| AbstractGameActionMessage, target_id| i32);
impl_type!(GameActionFightReflectSpellMessage, 5531, base| AbstractGameActionMessage, target_id| i32);
impl_type!(GameActionFightSlideMessage, 5525, base| AbstractGameActionMessage, target_id| i32, start_cell_id| i16, end_cell_id| i16);
impl_type!(GameActionFightSpellCastMessage, 1010, base| AbstractGameActionFightTargetedAbilityMessage, spell_id| VarShort, spell_level| i8, portals_ids| Vec<i16>);
impl_type!(GameActionFightSpellCooldownVariationMessage, 6219, base| AbstractGameActionMessage, target_id| i32, spell_id| VarShort, value| VarShort);
impl_type!(GameActionFightSpellImmunityMessage, 6221, base| AbstractGameActionMessage, target_id| i32, spell_id| VarShort);
impl_type!(GameActionFightStealKamaMessage, 5535, base| AbstractGameActionMessage, target_id| i32, amount| VarInt);
impl_type!(GameActionFightSummonMessage, 5825, base| AbstractGameActionMessage, summon| GameFightFighterInformationsVariant);
impl_type!(GameActionFightTackledMessage, 1004, base| AbstractGameActionMessage, tacklers_ids| Vec<i32>);
impl_type!(GameActionFightTeleportOnSameMapMessage, 5528, base| AbstractGameActionMessage, target_id| i32, cell_id| i16);
impl_type!(GameActionFightThrowCharacterMessage, 5829, base| AbstractGameActionMessage, target_id| i32, cell_id| i16);
impl_type!(GameActionFightTriggerEffectMessage, 6147, base| GameActionFightDispellEffectMessage);
impl_type!(GameActionFightTriggerGlyphTrapMessage, 5741, base| AbstractGameActionMessage, mark_id| i16, triggering_character_id| i32, triggered_spell_id| VarShort);
impl_type!(GameActionFightUnmarkCellsMessage, 5570, base| AbstractGameActionMessage, mark_id| i16);
impl_type!(GameActionFightVanishMessage, 6217, base| AbstractGameActionMessage, target_id| i32);

impl_type!(AbstractFightDispellableEffect, 206, uid| VarInt, target_id| i32, turn_duration| i16, dispelable| i8, spell_id| VarShort, effect_id| VarInt, parent_boost_uid| VarInt);
impl_type!(FightTemporaryBoostEffect, 209, base| AbstractFightDispellableEffect, delta| i16);
impl_type!(FightTemporaryBoostStateEffect, 214, base| FightTemporaryBoostEffect, state_id| i16);
impl_type!(FightTemporaryBoostWeaponDamagesEffect, 211, base| FightTemporaryBoostEffect, weapon_type_id| i16);
impl_type!(FightTemporarySpellBoostEffect, 207, base| FightTemporaryBoostEffect, boosted_spell_id| VarShort);
impl_type!(FightTemporarySpellImmunityEffect, 366, base| AbstractFightDispellableEffect, immune_spell_id| i32);
impl_type!(FightTriggeredEffect, 210, base| AbstractFightDispellableEffect, param1| i32, param2| i32, param3| i32, delay| i16);
impl_type!(GameActionMark, 351, mark_author_id| i32, mark_team_id| i8, mark_spell_id| i32, mark_spell_level| i8, mark_id| i16, mark_type| i8, markimpact_cell| i16, cells| Vec<GameActionMarkedCell>, active| bool);
impl_type!(GameActionMarkedCell, 85, cell_id| VarShort, zone_size| i8, cell_color| i32, cells_type| i8);
