use std::io::{Read, Write};
use io::Result;
use protocol::*;
 use protocol::game::context::MapCoordinatesExtended;
impl_type!(AbstractPartyEventMessage, 6273, base| AbstractPartyMessage);
impl_type!(AbstractPartyMessage, 6274, party_id| VarInt);
impl_type!(DungeonPartyFinderAvailableDungeonsMessage, 6242, dungeon_ids| Vec<VarShort>);
impl_type!(DungeonPartyFinderAvailableDungeonsRequestMessage, 6240);
impl_type!(DungeonPartyFinderListenErrorMessage, 6248, dungeon_id| VarShort);
impl_type!(DungeonPartyFinderListenRequestMessage, 6246, dungeon_id| VarShort);
impl_type!(DungeonPartyFinderRegisterErrorMessage, 6243);
impl_type!(DungeonPartyFinderRegisterRequestMessage, 6249, dungeon_ids| Vec<VarShort>);
impl_type!(DungeonPartyFinderRegisterSuccessMessage, 6241, dungeon_ids| Vec<VarShort>);
impl_type!(DungeonPartyFinderRoomContentMessage, 6247, dungeon_id| VarShort, players| Vec<DungeonPartyFinderPlayer>);
impl_type!(DungeonPartyFinderRoomContentUpdateMessage, 6250, dungeon_id| VarShort, added_players| Vec<DungeonPartyFinderPlayer>, removed_players_ids| Vec<VarInt>);
impl_type!(PartyAbdicateThroneMessage, 6080, base| AbstractPartyMessage, player_id| VarInt);
impl_type!(PartyAcceptInvitationMessage, 5580, base| AbstractPartyMessage);
impl_type!(PartyCancelInvitationMessage, 6254, base| AbstractPartyMessage, guest_id| VarInt);
impl_type!(PartyCancelInvitationNotificationMessage, 6251, base| AbstractPartyEventMessage, canceler_id| VarInt, guest_id| VarInt);
impl_type!(PartyCannotJoinErrorMessage, 5583, base| AbstractPartyMessage, reason| i8);
impl_type!(PartyDeletedMessage, 6261, base| AbstractPartyMessage);
impl_type!(PartyFollowMemberRequestMessage, 5577, base| AbstractPartyMessage, player_id| VarInt);
impl_type!(PartyFollowStatusUpdateMessage, 5581, base| AbstractPartyMessage, success| bool, followed_id| VarInt);
impl_type!(PartyFollowThisMemberRequestMessage, 5588, base| PartyFollowMemberRequestMessage, enabled| bool);
impl_type!(PartyInvitationArenaRequestMessage, 6283, base| PartyInvitationRequestMessage);
impl_type!(PartyInvitationCancelledForGuestMessage, 6256, base| AbstractPartyMessage, canceler_id| VarInt);
impl_type!(PartyInvitationDetailsMessage, 6263, base| AbstractPartyMessage, party_type| i8, party_name| String, from_id| VarInt, from_name| String, leader_id| VarInt, members| Vec<PartyInvitationMemberInformations>, guests| Vec<PartyGuestInformations>);
impl_type!(PartyInvitationDetailsRequestMessage, 6264, base| AbstractPartyMessage);
impl_type!(PartyInvitationDungeonDetailsMessage, 6262, base| PartyInvitationDetailsMessage, dungeon_id| VarShort, players_dungeon_ready| Vec<bool>);
impl_type!(PartyInvitationDungeonMessage, 6244, base| PartyInvitationMessage, dungeon_id| VarShort);
impl_type!(PartyInvitationDungeonRequestMessage, 6245, base| PartyInvitationRequestMessage, dungeon_id| VarShort);
impl_type!(PartyInvitationMessage, 5586, base| AbstractPartyMessage, party_type| i8, party_name| String, max_participants| i8, from_id| VarInt, from_name| String, to_id| VarInt);
impl_type!(PartyInvitationRequestMessage, 5585, name| String);
impl_type!(PartyJoinMessage, 5576, base| AbstractPartyMessage, party_type| i8, party_leader_id| VarInt, max_participants| i8, members| Vec<PartyMemberInformationsVariant>, guests| Vec<PartyGuestInformations>, restricted| bool, party_name| String);
impl_type!(PartyKickedByMessage, 5590, base| AbstractPartyMessage, kicker_id| VarInt);
impl_type!(PartyKickRequestMessage, 5592, base| AbstractPartyMessage, player_id| VarInt);
impl_type!(PartyLeaderUpdateMessage, 5578, base| AbstractPartyEventMessage, party_leader_id| VarInt);
impl_type!(PartyLeaveMessage, 5594, base| AbstractPartyMessage);
impl_type!(PartyLeaveRequestMessage, 5593, base| AbstractPartyMessage);
impl_type!(PartyLocateMembersMessage, 5595, base| AbstractPartyMessage, geopositions| Vec<PartyMemberGeoPosition>);
impl_type!(PartyLoyaltyStatusMessage, 6270, base| AbstractPartyMessage, loyal| bool);
impl_type!(PartyMemberEjectedMessage, 6252, base| PartyMemberRemoveMessage, kicker_id| VarInt);
impl_type!(PartyMemberInFightMessage, 6342, base| AbstractPartyMessage, reason| i8, member_id| VarInt, member_account_id| i32, member_name| String, fight_id| i32, fight_map| MapCoordinatesExtended, time_before_fight_start| VarShort);
impl_type!(PartyMemberRemoveMessage, 5579, base| AbstractPartyEventMessage, leaving_player_id| VarInt);
impl_type!(PartyModifiableStatusMessage, 6277, base| AbstractPartyMessage, enabled| bool);
impl_type!(PartyNameSetErrorMessage, 6501, base| AbstractPartyMessage, result| i8);
impl_type!(PartyNameSetRequestMessage, 6503, base| AbstractPartyMessage, party_name| String);
impl_type!(PartyNameUpdateMessage, 6502, base| AbstractPartyMessage, party_name| String);
impl_type!(PartyNewGuestMessage, 6260, base| AbstractPartyEventMessage, guest| PartyGuestInformations);
impl_type!(PartyNewMemberMessage, 6306, base| PartyUpdateMessage);
impl_type!(PartyPledgeLoyaltyRequestMessage, 6269, base| AbstractPartyMessage, loyal| bool);
impl_type!(PartyRefuseInvitationMessage, 5582, base| AbstractPartyMessage);
impl_type!(PartyRefuseInvitationNotificationMessage, 5596, base| AbstractPartyEventMessage, guest_id| VarInt);
impl_type!(PartyRestrictedMessage, 6175, base| AbstractPartyMessage, restricted| bool);
impl_type!(PartyStopFollowRequestMessage, 5574, base| AbstractPartyMessage);
impl_type!(PartyUpdateLightMessage, 6054, base| AbstractPartyEventMessage, id| VarInt, life_points| VarInt, max_life_points| VarInt, prospecting| VarShort, regen_rate| i8);
impl_type!(PartyUpdateMessage, 5575, base| AbstractPartyEventMessage, member_informations| PartyMemberInformationsVariant);
 use protocol::game::context::roleplay::party::companion::PartyCompanionBaseInformations; use protocol::game::character::status::PlayerStatusVariant; use protocol::game::context::roleplay::party::companion::PartyCompanionMemberInformations; use protocol::game::look::EntityLook;
impl_type!(DungeonPartyFinderPlayer, 373, player_id| VarInt, player_name| String, breed| i8, sex| bool, level| i8);
impl_type!(NamedPartyTeam, 469, team_id| i8, party_name| String);
impl_type!(NamedPartyTeamWithOutcome, 470, team| NamedPartyTeam, outcome| VarShort);
impl_type!(PartyGuestInformations, 374, guest_id| i32, host_id| i32, name| String, guest_look| EntityLook, breed| i8, sex| bool, status| PlayerStatusVariant, companions| Vec<PartyCompanionBaseInformations>);
impl_type!(PartyInvitationMemberInformations, 376, base| CharacterBaseInformations, world_x| i16, world_y| i16, map_id| i32, sub_area_id| VarShort, companions| Vec<PartyCompanionBaseInformations>);
impl_type!(PartyMemberArenaInformations, 391, base| PartyMemberInformations, rank| VarShort);
impl_type!(PartyMemberGeoPosition, 378, member_id| i32, world_x| i16, world_y| i16, map_id| i32, sub_area_id| VarShort);
impl_type!(PartyMemberInformations, 90, base| CharacterBaseInformations, life_points| VarInt, max_life_points| VarInt, prospecting| VarShort, regen_rate| i8, initiative| VarShort, alignment_side| i8, world_x| i16, world_y| i16, map_id| i32, sub_area_id| VarShort, status| PlayerStatusVariant, companions| Vec<PartyCompanionMemberInformations>);
