pub mod treasure_hunt;
pub mod quest;
pub mod party;
pub mod job;
pub mod fight;
use std::io::{Read, Write};
use std::io::Result;
use protocol::*;
use types::game::character::alignment::ActorAlignmentInformations; use variants::PortalInformationVariant; use types::game::look::IndexedEntityLook;  use variants::HumanInformationsVariant; use variants::HumanOptionVariant; use types::game::context::roleplay::quest::GameRolePlayNpcQuestFlag; use types::game::look::EntityLook; use types::game::guild::GuildEmblem; use types::game::character::restriction::ActorRestrictionsInformations; use types::game::context::GameContextActorInformations; use variants::GroupMonsterStaticInformationsVariant; use variants::PrismInformationVariant; use types::game::social::AbstractSocialGroupInfos; use types::game::context::MapCoordinatesExtended;
impl_type!(AllianceInformations, 417, base| BasicNamedAllianceInformations, alliance_emblem| GuildEmblem);
impl_type!(AlternativeMonstersInGroupLightInformations, 394, player_count| i32, monsters| Vec<MonsterInGroupLightInformations>);
impl_type!(AtlasPointsInformations, 175, type_| i8, coords| Vec<MapCoordinatesExtended>);
impl_type!(BasicAllianceInformations, 419, base| AbstractSocialGroupInfos, alliance_id| VarInt, alliance_tag| String);
impl_type!(BasicGuildInformations, 365, base| AbstractSocialGroupInfos, guild_id| VarInt, guild_name| String, guild_level| i8);
impl_type!(BasicNamedAllianceInformations, 418, base| BasicAllianceInformations, alliance_name| String);
impl_type!(GameRolePlayActorInformations, 141, base| GameContextActorInformations);
impl_type!(GameRolePlayCharacterInformations, 36, base| GameRolePlayHumanoidInformations, alignment_infos| ActorAlignmentInformations);
impl_type!(GameRolePlayGroupMonsterInformations, 160, base| GameRolePlayActorInformations, key_ring_bonus| Flag, has_hardcore_drop| Flag, has_ava_reward_token| Flag, static_infos| GroupMonsterStaticInformationsVariant, creation_time| f64, age_bonus_rate| i32, loot_share| i8, alignment_side| i8);
impl_type!(GameRolePlayGroupMonsterWaveInformations, 464, base| GameRolePlayGroupMonsterInformations, nb_waves| i8, alternatives| Vec<GroupMonsterStaticInformationsVariant>);
impl_type!(GameRolePlayHumanoidInformations, 159, base| GameRolePlayNamedActorInformations, humanoid_info| HumanInformationsVariant, account_id| i32);
impl_type!(GameRolePlayMerchantInformations, 129, base| GameRolePlayNamedActorInformations, sell_type| i8, options| Vec<HumanOptionVariant>);
impl_type!(GameRolePlayMountInformations, 180, base| GameRolePlayNamedActorInformations, owner_name| String, level| i8);
impl_type!(GameRolePlayMutantInformations, 3, base| GameRolePlayHumanoidInformations, monster_id| VarShort, power_level| i8);
impl_type!(GameRolePlayNamedActorInformations, 154, base| GameRolePlayActorInformations, name| String);
impl_type!(GameRolePlayNpcInformations, 156, base| GameRolePlayActorInformations, npc_id| VarShort, sex| bool, special_artwork_id| VarShort);
impl_type!(GameRolePlayNpcWithQuestInformations, 383, base| GameRolePlayNpcInformations, quest_flag| GameRolePlayNpcQuestFlag);
impl_type!(GameRolePlayPortalInformations, 467, base| GameRolePlayActorInformations, portal| PortalInformationVariant);
impl_type!(GameRolePlayPrismInformations, 161, base| GameRolePlayActorInformations, prism| PrismInformationVariant);
impl_type!(GameRolePlayTreasureHintInformations, 471, base| GameRolePlayActorInformations, npc_id| VarShort);
impl_type!(GroupMonsterStaticInformations, 140, main_creature_light_infos| MonsterInGroupLightInformations, underlings| Vec<MonsterInGroupInformations>);
impl_type!(GroupMonsterStaticInformationsWithAlternatives, 396, base| GroupMonsterStaticInformations, alternatives| Vec<AlternativeMonstersInGroupLightInformations>);
impl_type!(GuildInAllianceInformations, 420, base| GuildInformations, nb_members| i8, enabled| bool);
impl_type!(GuildInformations, 127, base| BasicGuildInformations, guild_emblem| GuildEmblem);
impl_type!(HumanInformations, 157, restrictions| ActorRestrictionsInformations, sex| bool, options| Vec<HumanOptionVariant>);
impl_type!(HumanOption, 406);
impl_type!(HumanOptionAlliance, 425, base| HumanOption, alliance_informations| AllianceInformations, aggressable| i8);
impl_type!(HumanOptionEmote, 407, base| HumanOption, emote_id| i8, emote_start_time| f64);
impl_type!(HumanOptionFollowers, 410, base| HumanOption, following_characters_look| Vec<IndexedEntityLook>);
impl_type!(HumanOptionGuild, 409, base| HumanOption, guild_informations| GuildInformations);
impl_type!(HumanOptionObjectUse, 449, base| HumanOption, delay_type_id| i8, delay_end_time| f64, object_gid| VarShort);
impl_type!(HumanOptionOrnament, 411, base| HumanOption, ornament_id| VarShort);
impl_type!(HumanOptionSkillUse, 495, base| HumanOption, element_id| VarInt, skill_id| VarShort, skill_end_time| f64);
impl_type!(HumanOptionTitle, 408, base| HumanOption, title_id| VarShort, title_param| String);
impl_type!(MonsterBoosts, 497, id| VarInt, xp_boost| VarShort, drop_boost| VarShort);
impl_type!(MonsterInGroupInformations, 144, base| MonsterInGroupLightInformations, look| EntityLook);
impl_type!(MonsterInGroupLightInformations, 395, creature_generic_id| i32, grade| i8);
impl_type!(ObjectItemInRolePlay, 198, cell_id| VarShort, object_gid| VarShort);
