use std::io::{Read, Write};
use io::Result;
use protocol::*;
 use protocol::game::house::HouseInformationsInside; use protocol::game::interactive::InteractiveElementVariant; use protocol::game::context::fight::FightCommonInformations; use protocol::game::house::HouseInformationsVariant; use protocol::game::interactive::StatedElement; use protocol::game::context::roleplay::party::NamedPartyTeam; use protocol::game::interactive::MapObstacle; use protocol::game::context::fight::GameFightFighterLightInformationsVariant; use protocol::game::context::fight::FightExternalInformations;
impl_type!(ChangeMapMessage, 221, map_id| i32);
impl_type!(CurrentMapMessage, 220, map_id| i32, map_key| String);
impl_type!(ErrorMapNotFoundMessage, 6197, map_id| i32);
impl_type!(GameRolePlayShowActorMessage, 5632, informations| GameRolePlayActorInformationsVariant);
impl_type!(GameRolePlayShowActorWithEventMessage, 6407, base| GameRolePlayShowActorMessage, actor_event_id| i8);
impl_type!(MapComplementaryInformationsDataInHouseMessage, 6130, base| MapComplementaryInformationsDataMessage, current_house| HouseInformationsInside);
impl_type!(MapComplementaryInformationsDataMessage, 226, sub_area_id| VarShort, map_id| i32, houses| Vec<HouseInformationsVariant>, actors| Vec<GameRolePlayActorInformationsVariant>, interactive_elements| Vec<InteractiveElementVariant>, stated_elements| Vec<StatedElement>, obstacles| Vec<MapObstacle>, fights| Vec<FightCommonInformations>);
impl_type!(MapComplementaryInformationsWithCoordsMessage, 6268, base| MapComplementaryInformationsDataMessage, world_x| i16, world_y| i16);
impl_type!(MapFightCountMessage, 210, fight_count| VarShort);
impl_type!(MapInformationsRequestMessage, 225, map_id| i32);
impl_type!(MapObstacleUpdateMessage, 6051, obstacles| Vec<MapObstacle>);
impl_type!(MapRunningFightDetailsExtendedMessage, 6500, base| MapRunningFightDetailsMessage, named_party_teams| Vec<NamedPartyTeam>);
impl_type!(MapRunningFightDetailsMessage, 5751, fight_id| i32, attackers| Vec<GameFightFighterLightInformationsVariant>, defenders| Vec<GameFightFighterLightInformationsVariant>);
impl_type!(MapRunningFightDetailsRequestMessage, 5750, fight_id| i32);
impl_type!(MapRunningFightListMessage, 5743, fights| Vec<FightExternalInformations>);
impl_type!(MapRunningFightListRequestMessage, 5742);
impl_type!(StopToListenRunningFightRequestMessage, 6124);
impl_type!(TeleportOnSameMapMessage, 6048, target_id| i32, cell_id| VarShort);
use protocol::game::context::roleplay::quest::GameRolePlayNpcQuestFlag;  use protocol::game::character::alignment::ActorAlignmentInformations; use protocol::game::character::restriction::ActorRestrictionsInformations; use protocol::game::guild::GuildEmblem; use protocol::game::prism::PrismInformationVariant; use protocol::game::context::roleplay::treasureHunt::PortalInformationVariant; use protocol::game::look::IndexedEntityLook; use protocol::game::context::MapCoordinatesExtended; use protocol::game::look::EntityLook;
impl_type!(AllianceInformations, 417, base| BasicNamedAllianceInformations, alliance_emblem| GuildEmblem);
impl_type!(AlternativeMonstersInGroupLightInformations, 394, player_count| i32, monsters| Vec<MonsterInGroupLightInformations>);
impl_type!(AtlasPointsInformations, 175, ttype| i8, coords| Vec<MapCoordinatesExtended>);
impl_type!(BasicAllianceInformations, 419, base| AbstractSocialGroupInfos, alliance_id| VarInt, alliance_tag| String);
impl_type!(BasicGuildInformations, 365, base| AbstractSocialGroupInfos, guild_id| VarInt, guild_name| String);
impl_type!(BasicNamedAllianceInformations, 418, base| BasicAllianceInformations, alliance_name| String);
impl_type!(GameRolePlayActorInformations, 141, base| GameContextActorInformations);
impl_type!(GameRolePlayCharacterInformations, 36, base| GameRolePlayHumanoidInformations, alignment_infos| ActorAlignmentInformations);
impl_type!(GameRolePlayGroupMonsterInformations, 160, base| GameRolePlayActorInformations, key_ring_bonus| Flag, has_hardcore_drop| Flag, has_a_v_a_reward_token| Flag, static_infos| GroupMonsterStaticInformationsVariant, age_bonus| i16, loot_share| i8, alignment_side| i8);
impl_type!(GameRolePlayGroupMonsterWaveInformations, 464, base| GameRolePlayGroupMonsterInformations, nb_waves| i8, alternatives| Vec<GroupMonsterStaticInformationsVariant>);
impl_type!(GameRolePlayHumanoidInformations, 159, base| GameRolePlayNamedActorInformations, humanoid_info| HumanInformationsVariant, account_id| i32);
impl_type!(GameRolePlayMerchantInformations, 129, base| GameRolePlayNamedActorInformations, sell_type| i8, options| Vec<HumanOptionVariant>);
impl_type!(GameRolePlayMountInformations, 180, base| GameRolePlayNamedActorInformations, owner_name| String, level| i8);
impl_type!(GameRolePlayMutantInformations, 3, base| GameRolePlayHumanoidInformations, monster_id| VarShort, power_level| i8);
impl_type!(GameRolePlayNamedActorInformations, 154, base| GameRolePlayActorInformations, name| String);
impl_type!(GameRolePlayNpcInformations, 156, base| GameRolePlayActorInformations, npc_id| VarShort, sex| bool, special_artwork_id| VarShort);
impl_type!(GameRolePlayNpcWithQuestInformations, 383, base| GameRolePlayNpcInformations, quest_flag| GameRolePlayNpcQuestFlag);
impl_type!(GameRolePlayPortalInformations, 467, base| GameRolePlayActorInformations, portal| PortalInformationVariant);
impl_type!(GameRolePlayPrismInformations, 161, base| GameRolePlayActorInformations, prism| PrismInformationVariant);
impl_type!(GameRolePlayTreasureHintInformations, 471, base| GameRolePlayActorInformations, npc_id| VarShort);
impl_type!(GroupMonsterStaticInformations, 140, main_creature_light_infos| MonsterInGroupLightInformations, underlings| Vec<MonsterInGroupInformations>);
impl_type!(GroupMonsterStaticInformationsWithAlternatives, 396, base| GroupMonsterStaticInformations, alternatives| Vec<AlternativeMonstersInGroupLightInformations>);
impl_type!(GuildInAllianceInformations, 420, base| GuildInformations, guild_level| i8, nb_members| i8, enabled| bool);
impl_type!(GuildInformations, 127, base| BasicGuildInformations, guild_emblem| GuildEmblem);
impl_type!(HumanInformations, 157, restrictions| ActorRestrictionsInformations, sex| bool, options| Vec<HumanOptionVariant>);
impl_type!(HumanOption, 406);
impl_type!(HumanOptionAlliance, 425, base| HumanOption, alliance_informations| AllianceInformations, aggressable| i8);
impl_type!(HumanOptionEmote, 407, base| HumanOption, emote_id| i8, emote_start_time| f64);
impl_type!(HumanOptionFollowers, 410, base| HumanOption, following_characters_look| Vec<IndexedEntityLook>);
impl_type!(HumanOptionGuild, 409, base| HumanOption, guild_informations| GuildInformations);
impl_type!(HumanOptionObjectUse, 449, base| HumanOption, delay_type_id| i8, delay_end_time| f64, object_g_i_d| VarShort);
impl_type!(HumanOptionOrnament, 411, base| HumanOption, ornament_id| VarShort);
impl_type!(HumanOptionTitle, 408, base| HumanOption, title_id| VarShort, title_param| String);
impl_type!(MonsterInGroupInformations, 144, base| MonsterInGroupLightInformations, look| EntityLook);
impl_type!(MonsterInGroupLightInformations, 395, creature_generic_id| i32, grade| i8);
impl_type!(ObjectItemInRolePlay, 198, cell_id| VarShort, object_g_i_d| VarShort);
