pub mod companion;
use std::io::{Read, Write};
use io::Result;
use protocol::*;
 use types::game::look::EntityLook; use types::game::character::choice::CharacterBaseInformations; use types::game::context::roleplay::party::companion::PartyCompanionBaseInformations; use variants::PlayerStatusVariant; use types::game::context::roleplay::party::companion::PartyCompanionMemberInformations;
impl_type!(DungeonPartyFinderPlayer, 373, player_id| VarInt, player_name| String, breed| i8, sex| bool, level| i8);
impl_type!(NamedPartyTeam, 469, team_id| i8, party_name| String);
impl_type!(NamedPartyTeamWithOutcome, 470, team| NamedPartyTeam, outcome| VarShort);
impl_type!(PartyGuestInformations, 374, guest_id| i32, host_id| i32, name| String, guest_look| EntityLook, breed| i8, sex| bool, status| PlayerStatusVariant, companions| Vec<PartyCompanionBaseInformations>);
impl_type!(PartyInvitationMemberInformations, 376, base| CharacterBaseInformations, world_x| i16, world_y| i16, map_id| i32, sub_area_id| VarShort, companions| Vec<PartyCompanionBaseInformations>);
impl_type!(PartyMemberArenaInformations, 391, base| PartyMemberInformations, rank| VarShort);
impl_type!(PartyMemberGeoPosition, 378, member_id| i32, world_x| i16, world_y| i16, map_id| i32, sub_area_id| VarShort);
impl_type!(PartyMemberInformations, 90, base| CharacterBaseInformations, life_points| VarInt, max_life_points| VarInt, prospecting| VarShort, regen_rate| i8, initiative| VarShort, alignment_side| i8, world_x| i16, world_y| i16, map_id| i32, sub_area_id| VarShort, status| PlayerStatusVariant, companions| Vec<PartyCompanionMemberInformations>);
