use std::io::{Read, Write};
use io::Result;
use protocol::*;
 use protocol::game::look::EntityLook;
impl_type!(JobAllowMultiCraftRequestMessage, 5748, enabled| bool);
impl_type!(JobBookSubscriptionMessage, 6593, added_or_deleted| bool, job_id| i8);
impl_type!(JobCrafterDirectoryAddMessage, 5651, list_entry| JobCrafterDirectoryListEntry);
impl_type!(JobCrafterDirectoryDefineSettingsMessage, 5649, settings| JobCrafterDirectorySettings);
impl_type!(JobCrafterDirectoryEntryMessage, 6044, player_info| JobCrafterDirectoryEntryPlayerInfo, job_info_list| Vec<JobCrafterDirectoryEntryJobInfo>, player_look| EntityLook);
impl_type!(JobCrafterDirectoryEntryRequestMessage, 6043, player_id| VarInt);
impl_type!(JobCrafterDirectoryListMessage, 6046, list_entries| Vec<JobCrafterDirectoryListEntry>);
impl_type!(JobCrafterDirectoryListRequestMessage, 6047, job_id| i8);
impl_type!(JobCrafterDirectoryRemoveMessage, 5653, job_id| i8, player_id| VarInt);
impl_type!(JobCrafterDirectorySettingsMessage, 5652, crafters_settings| Vec<JobCrafterDirectorySettings>);
impl_type!(JobDescriptionMessage, 5655, jobs_description| Vec<JobDescription>);
impl_type!(JobExperienceMultiUpdateMessage, 5809, experiences_update| Vec<JobExperience>);
impl_type!(JobExperienceUpdateMessage, 5654, experiences_update| JobExperience);
impl_type!(JobLevelUpMessage, 5656, new_level| i8, jobs_description| JobDescription);
impl_type!(JobMultiCraftAvailableSkillsMessage, 5747, base| JobAllowMultiCraftRequestMessage, player_id| VarInt, skills| Vec<VarShort>);
 use protocol::game::interactive::skill::SkillActionDescriptionVariant; use protocol::game::character::status::PlayerStatusVariant;
impl_type!(DecraftedItemStackInfo, 481, object_u_i_d| VarInt, bonus_min| Float, bonus_max| Float, runes_id| Vec<VarShort>, runes_qty| Vec<VarInt>);
impl_type!(JobCrafterDirectoryEntryJobInfo, 195, job_id| i8, job_level| i8, free| bool, min_level| i8);
impl_type!(JobCrafterDirectoryEntryPlayerInfo, 194, player_id| VarInt, player_name| String, alignment_side| i8, breed| i8, sex| bool, is_in_workshop| bool, world_x| i16, world_y| i16, map_id| i32, sub_area_id| VarShort, status| PlayerStatusVariant);
impl_type!(JobCrafterDirectoryListEntry, 196, player_info| JobCrafterDirectoryEntryPlayerInfo, job_info| JobCrafterDirectoryEntryJobInfo);
impl_type!(JobCrafterDirectorySettings, 97, job_id| i8, min_level| i8, free| bool);
impl_type!(JobDescription, 101, job_id| i8, skills| Vec<SkillActionDescriptionVariant>);
impl_type!(JobExperience, 98, job_id| i8, job_level| i8, job_x_p| VarLong, job_xp_level_floor| VarLong, job_xp_next_level_floor| VarLong);
