use std::io::{Read, Write};
use io::Result;
use protocol::*;
 use protocol::game::look::EntityLook;
impl_type!(GameCautiousMapMovementMessage, 6497, base| GameMapMovementMessage);
impl_type!(GameCautiousMapMovementRequestMessage, 6496, base| GameMapMovementRequestMessage);
impl_type!(GameContextCreateErrorMessage, 6024);
impl_type!(GameContextCreateMessage, 200, context| i8);
impl_type!(GameContextCreateRequestMessage, 250);
impl_type!(GameContextDestroyMessage, 201);
impl_type!(GameContextKickMessage, 6081, target_id| i32);
impl_type!(GameContextMoveElementMessage, 253, movement| EntityMovementInformations);
impl_type!(GameContextMoveMultipleElementsMessage, 254, movements| Vec<EntityMovementInformations>);
impl_type!(GameContextQuitMessage, 255);
impl_type!(GameContextReadyMessage, 6071, map_id| i32);
impl_type!(GameContextRefreshEntityLookMessage, 5637, id| i32, look| EntityLook);
impl_type!(GameContextRemoveElementMessage, 251, id| i32);
impl_type!(GameContextRemoveElementWithEventMessage, 6412, base| GameContextRemoveElementMessage, element_event_id| i8);
impl_type!(GameContextRemoveMultipleElementsMessage, 252, id| Vec<i32>);
impl_type!(GameContextRemoveMultipleElementsWithEventsMessage, 6416, base| GameContextRemoveMultipleElementsMessage, element_event_ids| Vec<u8>);
impl_type!(GameEntitiesDispositionMessage, 5696, dispositions| Vec<IdentifiedEntityDispositionInformations>);
impl_type!(GameEntityDispositionErrorMessage, 5695);
impl_type!(GameEntityDispositionMessage, 5693, disposition| IdentifiedEntityDispositionInformations);
impl_type!(GameMapChangeOrientationMessage, 946, orientation| ActorOrientation);
impl_type!(GameMapChangeOrientationRequestMessage, 945, direction| i8);
impl_type!(GameMapChangeOrientationsMessage, 6155, orientations| Vec<ActorOrientation>);
impl_type!(GameMapMovementCancelMessage, 953, cell_id| VarShort);
impl_type!(GameMapMovementConfirmMessage, 952);
impl_type!(GameMapMovementMessage, 951, key_movements| Vec<i16>, actor_id| i32);
impl_type!(GameMapMovementRequestMessage, 950, key_movements| Vec<i16>, map_id| i32);
impl_type!(GameMapNoMovementMessage, 954);
impl_type!(ShowCellMessage, 5612, source_id| i32, cell_id| VarShort);
impl_type!(ShowCellRequestMessage, 5611, cell_id| VarShort);
impl_type!(ShowCellSpectatorMessage, 6158, base| ShowCellMessage, player_name| String);
 use protocol::game::context::roleplay::AllianceInformations; use protocol::game::context::roleplay::GuildInformations; use protocol::game::look::EntityLook;
impl_type!(ActorOrientation, 353, id| i32, direction| i8);
impl_type!(EntityDispositionInformations, 60, cell_id| i16, direction| i8);
impl_type!(EntityMovementInformations, 63, id| i32, steps| Vec<u8>);
impl_type!(FightEntityDispositionInformations, 217, base| EntityDispositionInformations, carrying_character_id| i32);
impl_type!(GameContextActorInformations, 150, contextual_id| i32, look| EntityLook, disposition| EntityDispositionInformationsVariant);
impl_type!(GameRolePlayTaxCollectorInformations, 148, base| GameRolePlayActorInformations, identification| TaxCollectorStaticInformationsVariant, guild_level| i8, tax_collector_attack| i32);
impl_type!(IdentifiedEntityDispositionInformations, 107, base| EntityDispositionInformations, id| i32);
impl_type!(MapCoordinates, 174, world_x| i16, world_y| i16);
impl_type!(MapCoordinatesAndId, 392, base| MapCoordinates, map_id| i32);
impl_type!(MapCoordinatesExtended, 176, base| MapCoordinatesAndId, sub_area_id| VarShort);
impl_type!(TaxCollectorStaticExtendedInformations, 440, base| TaxCollectorStaticInformations, alliance_identity| AllianceInformations);
impl_type!(TaxCollectorStaticInformations, 147, first_name_id| VarShort, last_name_id| VarShort, guild_identity| GuildInformations);
