use std::io::{Read, Write};
use io::Result;
use protocol::*;
 use protocol::game::character::CharacterMinimalPlusLookInformationsVariant;
impl_type!(PrismAttackRequestMessage, 6042);
impl_type!(PrismFightAddedMessage, 6452, fight| PrismFightersInformation);
impl_type!(PrismFightAttackerAddMessage, 5893, sub_area_id| VarShort, fight_id| VarShort, attacker| CharacterMinimalPlusLookInformationsVariant);
impl_type!(PrismFightAttackerRemoveMessage, 5897, sub_area_id| VarShort, fight_id| VarShort, fighter_to_remove_id| VarInt);
impl_type!(PrismFightDefenderAddMessage, 5895, sub_area_id| VarShort, fight_id| VarShort, defender| CharacterMinimalPlusLookInformationsVariant);
impl_type!(PrismFightDefenderLeaveMessage, 5892, sub_area_id| VarShort, fight_id| VarShort, fighter_to_remove_id| VarInt);
impl_type!(PrismFightJoinLeaveRequestMessage, 5843, sub_area_id| VarShort, join| bool);
impl_type!(PrismFightRemovedMessage, 6453, sub_area_id| VarShort);
impl_type!(PrismFightStateUpdateMessage, 6040, state| i8);
impl_type!(PrismFightSwapRequestMessage, 5901, sub_area_id| VarShort, target_id| VarInt);
impl_type!(PrismInfoCloseMessage, 5853);
impl_type!(PrismInfoInValidMessage, 5859, reason| i8);
impl_type!(PrismInfoJoinLeaveRequestMessage, 5844, join| bool);
impl_type!(PrismModuleExchangeRequestMessage, 6531);
impl_type!(PrismSetSabotagedRefusedMessage, 6466, sub_area_id| VarShort, reason| i8);
impl_type!(PrismSetSabotagedRequestMessage, 6468, sub_area_id| VarShort);
impl_type!(PrismSettingsErrorMessage, 6442);
impl_type!(PrismSettingsRequestMessage, 6437, sub_area_id| VarShort, start_defense_time| i8);
impl_type!(PrismsInfoValidMessage, 6451, fights| Vec<PrismFightersInformation>);
impl_type!(PrismsListMessage, 6440, prisms| Vec<PrismSubareaEmptyInfoVariant>);
impl_type!(PrismsListRegisterMessage, 6441, listen| i8);
impl_type!(PrismsListUpdateMessage, 6438, base| PrismsListMessage);
impl_type!(PrismUseRequestMessage, 6041);
 use protocol::game::context::roleplay::AllianceInformations; use protocol::game::fight::ProtectedEntityWaitingForHelpInfo; use protocol::game::character::CharacterMinimalPlusLookInformationsVariant;
impl_type!(AllianceInsiderPrismInformation, 431, base| PrismInformation, last_time_slot_modification_date| i32, last_time_slot_modification_author_guild_id| VarInt, last_time_slot_modification_author_id| VarInt, last_time_slot_modification_author_name| String, modules_item_ids| Vec<VarInt>);
impl_type!(AlliancePrismInformation, 427, base| PrismInformation, alliance| AllianceInformations);
impl_type!(PrismFightersInformation, 443, sub_area_id| VarShort, waiting_for_help_info| ProtectedEntityWaitingForHelpInfo, ally_characters_informations| Vec<CharacterMinimalPlusLookInformationsVariant>, enemy_characters_informations| Vec<CharacterMinimalPlusLookInformationsVariant>);
impl_type!(PrismGeolocalizedInformation, 434, base| PrismSubareaEmptyInfo, world_x| i16, world_y| i16, map_id| i32, prism| PrismInformationVariant);
impl_type!(PrismInformation, 428, type_id| i8, state| i8, next_vulnerability_date| i32, placement_date| i32, reward_token_count| VarInt);
impl_type!(PrismSubareaEmptyInfo, 438, sub_area_id| VarShort, alliance_id| VarInt);
