use std::io::{Read, Write};
use io::Result;
use protocol::*;
use types::game::character::alignment::ActorAlignmentInformations; use variants::GameFightMinimalStatsVariant;  use variants::FightTeamMemberInformationsVariant; use types::game::context::roleplay::BasicAllianceInformations; use types::game::context::GameContextActorInformations; use variants::FightTeamInformationsVariant; use variants::FightResultAdditionalDataVariant; use types::game::context::roleplay::BasicGuildInformations; use types::game::character::status::PlayerStatus;
impl_type!(AbstractFightTeamInformations, 116, team_id| i8, leader_id| i32, team_side| i8, team_type_id| i8, nb_waves| i8);
impl_type!(FightAllianceTeamInformations, 439, base| FightTeamInformations, relation| i8);
impl_type!(FightCommonInformations, 43, fight_id| i32, fight_type| i8, fight_teams| Vec<FightTeamInformationsVariant>, fight_teams_positions| Vec<VarShort>, fight_teams_options| Vec<FightOptionsInformations>);
impl_type!(FightExternalInformations, 117, fight_id| i32, fight_type| i8, fight_start| i32, fight_spectator_locked| bool);
impl_type!(FightLoot, 41, objects| Vec<VarShort>, kamas| VarInt);
impl_type!(FightOptionsInformations, 20, is_secret| Flag, is_restricted_to_party_only| Flag, is_closed| Flag, is_asking_for_help| Flag);
impl_type!(FightResultAdditionalData, 191);
impl_type!(FightResultExperienceData, 192, base| FightResultAdditionalData, show_experience| Flag, show_experience_level_floor| Flag, show_experience_next_level_floor| Flag, show_experience_fight_delta| Flag, show_experience_for_guild| Flag, show_experience_for_mount| Flag, is_incarnation_experience| Flag, experience| VarLong, experience_level_floor| VarLong, experience_next_level_floor| f64, experience_fight_delta| VarInt, experience_for_guild| VarInt, experience_for_mount| VarInt, reroll_experience_mul| i8);
impl_type!(FightResultFighterListEntry, 189, base| FightResultListEntry, id| i32, alive| bool);
impl_type!(FightResultListEntry, 16, outcome| VarShort, wave| i8, rewards| FightLoot);
impl_type!(FightResultMutantListEntry, 216, base| FightResultFighterListEntry, level| VarShort);
impl_type!(FightResultPlayerListEntry, 24, base| FightResultFighterListEntry, level| i8, additional| Vec<FightResultAdditionalDataVariant>);
impl_type!(FightResultPvpData, 190, base| FightResultAdditionalData, grade| i8, min_honor_for_grade| VarShort, max_honor_for_grade| VarShort, honor| VarShort, honor_delta| VarShort);
impl_type!(FightResultTaxCollectorListEntry, 84, base| FightResultFighterListEntry, level| i8, guild_info| BasicGuildInformations, experience_for_guild| i32);
impl_type!(FightTeamInformations, 33, base| AbstractFightTeamInformations, team_members| Vec<FightTeamMemberInformationsVariant>);
impl_type!(FightTeamLightInformations, 115, base| AbstractFightTeamInformations, has_friend| Flag, has_guild_member| Flag, has_alliance_member| Flag, has_group_member| Flag, has_my_tax_collector| Flag, team_members_count| i8, mean_level| VarInt);
impl_type!(FightTeamMemberCharacterInformations, 13, base| FightTeamMemberInformations, name| String, level| i8);
impl_type!(FightTeamMemberCompanionInformations, 451, base| FightTeamMemberInformations, companion_id| i8, level| i8, master_id| i32);
impl_type!(FightTeamMemberInformations, 44, id| i32);
impl_type!(FightTeamMemberMonsterInformations, 6, base| FightTeamMemberInformations, monster_id| i32, grade| i8);
impl_type!(FightTeamMemberTaxCollectorInformations, 177, base| FightTeamMemberInformations, first_name_id| VarShort, last_name_id| VarShort, level| i8, guild_id| VarInt, uid| VarInt);
impl_type!(FightTeamMemberWithAllianceCharacterInformations, 426, base| FightTeamMemberCharacterInformations, alliance_infos| BasicAllianceInformations);
impl_type!(GameFightAIInformations, 151, base| GameFightFighterInformations);
impl_type!(GameFightCharacterInformations, 46, base| GameFightFighterNamedInformations, level| i8, alignment_infos| ActorAlignmentInformations, breed| i8, sex| bool);
impl_type!(GameFightCompanionInformations, 450, base| GameFightFighterInformations, companion_generic_id| i8, level| i8, master_id| i32);
impl_type!(GameFightFighterCompanionLightInformations, 454, base| GameFightFighterLightInformations, companion_id| i8, master_id| i32);
impl_type!(GameFightFighterInformations, 143, base| GameContextActorInformations, team_id| i8, wave| i8, alive| bool, stats| GameFightMinimalStatsVariant, previous_positions| Vec<VarShort>);
impl_type!(GameFightFighterLightInformations, 413, sex| Flag, alive| Flag, id| i32, wave| i8, level| VarShort, breed| i8);
impl_type!(GameFightFighterMonsterLightInformations, 455, base| GameFightFighterLightInformations, creature_generic_id| VarShort);
impl_type!(GameFightFighterNamedInformations, 158, base| GameFightFighterInformations, name| String, status| PlayerStatus);
impl_type!(GameFightFighterNamedLightInformations, 456, base| GameFightFighterLightInformations, name| String);
impl_type!(GameFightFighterTaxCollectorLightInformations, 457, base| GameFightFighterLightInformations, first_name_id| VarShort, last_name_id| VarShort);
impl_type!(GameFightMinimalStats, 31, life_points| VarInt, max_life_points| VarInt, base_max_life_points| VarInt, permanent_damage_percent| VarInt, shield_points| VarInt, action_points| VarShort, max_action_points| VarShort, movement_points| VarShort, max_movement_points| VarShort, summoner| i32, summoned| bool, neutral_element_resist_percent| VarShort, earth_element_resist_percent| VarShort, water_element_resist_percent| VarShort, air_element_resist_percent| VarShort, fire_element_resist_percent| VarShort, neutral_element_reduction| VarShort, earth_element_reduction| VarShort, water_element_reduction| VarShort, air_element_reduction| VarShort, fire_element_reduction| VarShort, critical_damage_fixed_resist| VarShort, push_damage_fixed_resist| VarShort, pvp_neutral_element_resist_percent| VarShort, pvp_earth_element_resist_percent| VarShort, pvp_water_element_resist_percent| VarShort, pvp_air_element_resist_percent| VarShort, pvp_fire_element_resist_percent| VarShort, pvp_neutral_element_reduction| VarShort, pvp_earth_element_reduction| VarShort, pvp_water_element_reduction| VarShort, pvp_air_element_reduction| VarShort, pvp_fire_element_reduction| VarShort, dodge_pa_lost_probability| VarShort, dodge_pm_lost_probability| VarShort, tackle_block| VarShort, tackle_evade| VarShort, invisibility_state| i8);
impl_type!(GameFightMinimalStatsPreparation, 360, base| GameFightMinimalStats, initiative| VarInt);
impl_type!(GameFightMonsterInformations, 29, base| GameFightAIInformations, creature_generic_id| VarShort, creature_grade| i8);
impl_type!(GameFightMonsterWithAlignmentInformations, 203, base| GameFightMonsterInformations, alignment_infos| ActorAlignmentInformations);
impl_type!(GameFightMutantInformations, 50, base| GameFightFighterNamedInformations, power_level| i8);
impl_type!(GameFightResumeSlaveInfo, 364, slave_id| i32, spell_cooldowns| Vec<GameFightSpellCooldown>, summon_count| i8, bomb_count| i8);
impl_type!(GameFightSpellCooldown, 205, spell_id| i32, cooldown| i8);
impl_type!(GameFightTaxCollectorInformations, 48, base| GameFightAIInformations, first_name_id| VarShort, last_name_id| VarShort, level| i8);
